#!/usr/bin/python
import os, sys

base = os.path.dirname(os.path.abspath(__file__)) #get cwd
sys.path.append(base) #add cwd libs to path
os.environ['CLUSTOCONFIG'] = '%s/clusto.conf' % base #use config in cwd
execfile('%s/virtualenv/bin/activate_this.py' % base, dict(__file__='%s/virtualenv/bin/activate_this.py' % base)) #load the virtualenv for this cwd

import clusto
import kfxclusto

if __name__ == '__main__':
    #if run as a script, start the clusto script name supplied

    newprog = sys.argv.pop(1)
    sys.argv[0] = newprog
    #execfile("%s/virtualenv/bin/%s" % (base, newprog))
    
    from pkg_resources import load_entry_point

    sys.exit(
        load_entry_point('clusto', 'console_scripts', newprog)()
    )
